### ISSUE TITLE
Standard Report Values

### ISSUE THREAD

**Issue by adeniwale** [epimorphics/standard-reports-ui#10] opened 2016-02-04 12:12 UTC
The values of some of the Standard Report statistics are not as expected. I checked some of these values by searching the ppd website and they are not exactly the same as those in the standard reports. Please see attached results file.
[Test Result Report.docx](https://github.com/epimorphics/standard-reports-ui/files/117374/Test.Result.Report.docx)

**Comment by der** [comment] 2016-02-04 12:44
Will need more details on how you are computing the expected values to diagnose this.

One possibility is simply that your are requesting standard reports that have been requested before and so are in the cache. Since the data changed a few days ago then the cached reports will be out of date. I have cleared the cache (there's Trello card that automating that will be part of moving to production).

Please can you run the test or part of the test again and see if that has made any difference.

**Comment by ijdickinson** [comment] 2016-02-04 12:44
Can you please explain your test methodology in more detail. How did you get the expected values, and which PPD datasets were you using (staging or live)?

**Comment by adeniwale** [comment] 2016-02-04 13:14
I will generate the standard reports again. The ones I am using were generated a while ago. What the automated test does is to use sparql query to get the records for a particular geographical area and these are then counted. The approach document is attached to Trello card TA-10.

**Comment by adeniwale** [comment] 2016-02-04 16:27
I have obtained a better result after generation new standard reports and 
[Test Result Report.docx](https://github.com/epimorphics/standard-reports-ui/files/117774/Test.Result.Report.docx)
running the test again. Please see attached...

**Comment by der** [comment] 2016-02-04 16:33
OK, so now let's pick on of the remaining discrepancies where there is a small enough number we can check by hand such as:

```
VALIDATION TEST REPORT FOR "AVGPRICE-PCAREA-LA-BY-PCDISTRICT-OLD-2015" STANDARD REPORT . .

ERROR!! - LA8 POSTCODE DISTRICT: FLAT-MAISONETTE SALES => (Actual-6|Expected-7): AVERAGE PRICE => (Actual-212548|Expected-223612)
```

If you could tell us the precise query you are running to get the expected count of 7 then we can check against the query the report generator uses to get a count of 6 and track down the cause of the diffference

**Comment by ijdickinson** [comment] 2016-02-04 16:38
Victor -
Can you please attach these test results as text files in future, or just copy them directly into the issue? There really is no need for them to be embedded in an attached MS Word document. 

I agree with Dave, we need to see the query that you are actually running. I looked at the TA-10 document you referred to, but it does not contain any details of the queries that you are using to compare against the results that the app gets.

**Comment by MalcolmShazell** [comment] 2016-02-04 16:48
Victor, this is the Sparql I would expect to be running to validate the test and it does generate 6 results in the PPD report builder

prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix sr: <http://data.ordnancesurvey.co.uk/ontology/spatialrelations/>
prefix lrhpi: <http://landregistry.data.gov.uk/def/hpi/>
prefix lrppi: <http://landregistry.data.gov.uk/def/ppi/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix lrcommon: <http://landregistry.data.gov.uk/def/common/>

PREFIX  text: <http://jena.apache.org/text#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  ppd:  <http://landregistry.data.gov.uk/def/ppi/>
PREFIX  lrcommon: <http://landregistry.data.gov.uk/def/common/>

SELECT  ?item ?ppd_propertyAddress ?ppd_transactionDate ?ppd_newBuild ?ppd_propertyType ?ppd_hasTransaction ?ppd_pricePaid ?ppd_transactionCategory ?ppd_transactionId ?ppd_estateType ?ppd_propertyAddressCounty ?ppd_propertyAddressDistrict ?ppd_propertyAddressLocality ?ppd_propertyAddressPaon ?ppd_propertyAddressPostcode ?ppd_propertyAddressSaon ?ppd_propertyAddressStreet ?ppd_propertyAddressTown ?ppd_recordStatus
WHERE
  { ?ppd_propertyAddress text:query _:b0 .
    _:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> lrcommon:postcode .
    _:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b1 .
    _:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "( la8 )" .
    _:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b2 .
    _:b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> 3000000 .
    _:b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
    ?item ppd:propertyAddress ?ppd_propertyAddress .
    ?item ppd:transactionDate ?ppd_transactionDate .
    ?item ppd:newBuild false .
    ?item ppd:propertyType lrcommon:flat-maisonette .
    ?item ppd:hasTransaction ?ppd_hasTransaction .
    ?item ppd:pricePaid ?ppd_pricePaid .
    ?item ppd:transactionCategory ?ppd_transactionCategory .
    ?item ppd:transactionId ?ppd_transactionId
    OPTIONAL
      { ?item ppd:estateType ?ppd_estateType }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:county ?ppd_propertyAddressCounty }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:district ?ppd_propertyAddressDistrict }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:locality ?ppd_propertyAddressLocality }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:paon ?ppd_propertyAddressPaon }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:postcode ?ppd_propertyAddressPostcode }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:saon ?ppd_propertyAddressSaon }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:street ?ppd_propertyAddressStreet }
    OPTIONAL
      { ?ppd_propertyAddress lrcommon:town ?ppd_propertyAddressTown }
    OPTIONAL
      { ?item ppd:recordStatus ?ppd_recordStatus }
    FILTER ( ?ppd_transactionDate >= "2015-01-01"^^xsd:date )
    FILTER ( ?ppd_transactionDate <= "2015-12-31"^^xsd:date )
    BIND(false AS ?ppd_newBuild)
    BIND(lrcommon:flat-maisonette AS ?ppd_propertyType)

**Comment by adeniwale** [comment] 2016-02-04 16:57
I have checked the outstanding errors on the search ppd website and they are all correct except:

VALIDATION TEST REPORT FOR "AVGPRICE-REGION-SOUTH_WEST-BY-COUNTY-NEW-2015" STANDARD REPORT . . . .
ERROR!! - SWINDON COUNTY: FLAT-MAISONETTE SALES => (Actual-103|Expected-102): AVERAGE PRICE => (Actual-142513|Expected-141311)

VALIDATION TEST REPORT FOR "BANDED-REGION-SOUTH_WEST-BY-COUNTY-NEW-2015" STANDARD REPORT . . . .
ERROR!! - SWINDON COUNTY: BANDING => 200,001 - 300,000: FLAT-MAISONETTE SALES => (Actual-9|Expected-8)

**Comment by adeniwale** [comment] 2016-02-04 16:59
I'll check my test code checking the PC Area values

**Comment by MalcolmShazell** [comment] 2016-02-05 12:05
victor, just done a simple check trying to re-build a search based on the description you gave above and for the price band you identify I'm getting 8 new build records and 6 not new build

**Comment by ijdickinson** [comment] 2020-08-26 16:38
Assuming this is now obsolete. Please re-open if more investigation is needed

**Closed by ijdickinson** 2020-08-26 16:38 UTC
